version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fastapi-app
        ports:
            - "8000:8000"
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - .:/app
        networks:
            - app-network

    redis:
        image: redis:6
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge